env:
  es2017: true
  node: true
  browser: true
parserOptions:
  ecmaVersion: 2020
extends:
  - 'eslint:recommended'
  - 'plugin:node/recommended'
  - 'prettier'
ignorePatterns:
  - 'test/webroot/**'
rules:
  no-async-promise-executor: 'off'
  no-empty:
  - error
  - allowEmptyCatch: true
  no-prototype-builtins: 'off'
  "node/no-extraneous-require": 'off'
  "node/no-unsupported-features/es-syntax": 'error'
