#!/usr/bin/env node

// CSS parsers
var cssParse = require('css-parse'),
	cssOm = require('cssom');

// load CSS file
var fileName = '/home/macbre/github/css/wikia.css',
	css = require('fs').readFileSync(fileName).toString();

// remove CSS comments
css = css.replace(/\/\*[^\*]+\*\//g, '');

// CSS parse
var time = Date.now();
var res = new cssParse(css);
console.log("css-parse [ms]: " + (Date.now() - time));
console.log('Rules: ' + res.stylesheet.rules.length);
console.log('CSS size [kB]: ' + (css.length/1024).toFixed(2));

console.log(res);

// CSS OM
var time = Date.now();
var res = cssOm.parse(css);
console.log("cssom [ms]: " + (Date.now() - time));
console.log('Rules: ' + res.cssRules.length);

console.log(res);

